pub mod api_proxy;
pub mod builtin_llm_commands;
pub mod cli_commands;
pub mod dashboard_commands;
pub mod notepad_commands;
pub mod proxy_commands;
pub mod quickapps_commands;
pub mod system_commands;
pub mod web_ai_commands;
