; Generated by scripts/generate-modules-nsh.mjs. Do not edit by hand.
; Fresh installs default to Core only. Rerunning Setup preselects installed modules.

!macro NSIS_HOOK_PREINSTALL
  !insertmacro CheckIfAppIsRunning "clx-ai-companion-sidecar.exe" "AI Companion"
  !insertmacro CheckIfAppIsRunning "clx-api-client-sidecar.exe" "API Client"
  !insertmacro CheckIfAppIsRunning "clx-buzz-sidecar.exe" "Buzz Workspace"
  !insertmacro CheckIfAppIsRunning "clx-cli-proxy-sidecar.exe" "CliProxyAI"
  !insertmacro CheckIfAppIsRunning "clx-local-llm-sidecar.exe" "Local LLM (Candle Runtime)"
  !insertmacro CheckIfAppIsRunning "clx-nes-sidecar.exe" "NES Emulator & Netplay"
  !insertmacro CheckIfAppIsRunning "clx-quickapps-sidecar.exe" "Quick Apps"
  !insertmacro CheckIfAppIsRunning "clx-ssh-sidecar.exe" "Remote SSH & Monitoring"
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  !insertmacro CheckIfAppIsRunning "clx-ai-companion-sidecar.exe" "AI Companion"
  !insertmacro CheckIfAppIsRunning "clx-api-client-sidecar.exe" "API Client"
  !insertmacro CheckIfAppIsRunning "clx-buzz-sidecar.exe" "Buzz Workspace"
  !insertmacro CheckIfAppIsRunning "clx-cli-proxy-sidecar.exe" "CliProxyAI"
  !insertmacro CheckIfAppIsRunning "clx-local-llm-sidecar.exe" "Local LLM (Candle Runtime)"
  !insertmacro CheckIfAppIsRunning "clx-nes-sidecar.exe" "NES Emulator & Netplay"
  !insertmacro CheckIfAppIsRunning "clx-quickapps-sidecar.exe" "Quick Apps"
  !insertmacro CheckIfAppIsRunning "clx-ssh-sidecar.exe" "Remote SSH & Monitoring"
!macroend

!macro CLX_MODULE_INIT
  Call ClxInitializeModuleSelections
!macroend

!macro CLX_MODULE_SECTIONS
  Section /o "AI Companion" SEC_CLX_AI_COMPANION
    SetOutPath "$INSTDIR\modules\clx.ai-companion\0.1.0"
    File /a /r "D:\CLI-Ochestor\dist-packs\clx.ai-companion\0.1.0\*.*"
  SectionEnd

  Section /o "API Client" SEC_CLX_API_CLIENT
    SetOutPath "$INSTDIR\modules\clx.api-client\0.1.0"
    File /a /r "D:\CLI-Ochestor\dist-packs\clx.api-client\0.1.0\*.*"
  SectionEnd

  Section /o "Buzz Workspace" SEC_CLX_BUZZ
    SetOutPath "$INSTDIR\modules\clx.buzz\0.1.0"
    File /a /r "D:\CLI-Ochestor\dist-packs\clx.buzz\0.1.0\*.*"
  SectionEnd

  Section /o "CliProxyAI" SEC_CLX_CLI_PROXY
    SetOutPath "$INSTDIR\modules\clx.cli-proxy\0.1.0"
    File /a /r "D:\CLI-Ochestor\dist-packs\clx.cli-proxy\0.1.0\*.*"
  SectionEnd

  Section /o "Local LLM (Candle Runtime)" SEC_CLX_LOCAL_LLM
    SetOutPath "$INSTDIR\modules\clx.local-llm\0.1.0"
    File /a /r "D:\CLI-Ochestor\dist-packs\clx.local-llm\0.1.0\*.*"
  SectionEnd

  Section /o "NES Emulator & Netplay" SEC_CLX_NES
    SetOutPath "$INSTDIR\modules\clx.nes\0.1.0"
    File /a /r "D:\CLI-Ochestor\dist-packs\clx.nes\0.1.0\*.*"
  SectionEnd

  Section /o "Mythical Pet Overlay" SEC_CLX_PET
    SetOutPath "$INSTDIR\modules\clx.pet\0.1.0"
    File /a /r "D:\CLI-Ochestor\dist-packs\clx.pet\0.1.0\*.*"
  SectionEnd

  Section /o "Quick Apps" SEC_CLX_QUICKAPPS
    SetOutPath "$INSTDIR\modules\clx.quickapps\0.1.0"
    File /a /r "D:\CLI-Ochestor\dist-packs\clx.quickapps\0.1.0\*.*"
  SectionEnd

  Section /o "Remote SSH & Monitoring" SEC_CLX_SSH
    SetOutPath "$INSTDIR\modules\clx.ssh\0.1.0"
    File /a /r "D:\CLI-Ochestor\dist-packs\clx.ssh\0.1.0\*.*"
  SectionEnd

  Section "-Apply module selection" SEC_CLX_MODULE_SELECTION
    SectionGetFlags ${SEC_CLX_AI_COMPANION} $R8
    IntOp $R8 $R8 & ${SF_SELECTED}
    ${If} $R8 != ${SF_SELECTED}
      RMDir /r "$INSTDIR\modules\clx.ai-companion"
    ${EndIf}
    SectionGetFlags ${SEC_CLX_API_CLIENT} $R8
    IntOp $R8 $R8 & ${SF_SELECTED}
    ${If} $R8 != ${SF_SELECTED}
      RMDir /r "$INSTDIR\modules\clx.api-client"
    ${EndIf}
    SectionGetFlags ${SEC_CLX_BUZZ} $R8
    IntOp $R8 $R8 & ${SF_SELECTED}
    ${If} $R8 != ${SF_SELECTED}
      RMDir /r "$INSTDIR\modules\clx.buzz"
    ${EndIf}
    SectionGetFlags ${SEC_CLX_CLI_PROXY} $R8
    IntOp $R8 $R8 & ${SF_SELECTED}
    ${If} $R8 != ${SF_SELECTED}
      RMDir /r "$INSTDIR\modules\clx.cli-proxy"
    ${EndIf}
    SectionGetFlags ${SEC_CLX_LOCAL_LLM} $R8
    IntOp $R8 $R8 & ${SF_SELECTED}
    ${If} $R8 != ${SF_SELECTED}
      RMDir /r "$INSTDIR\modules\clx.local-llm"
    ${EndIf}
    SectionGetFlags ${SEC_CLX_NES} $R8
    IntOp $R8 $R8 & ${SF_SELECTED}
    ${If} $R8 != ${SF_SELECTED}
      RMDir /r "$INSTDIR\modules\clx.nes"
    ${EndIf}
    SectionGetFlags ${SEC_CLX_PET} $R8
    IntOp $R8 $R8 & ${SF_SELECTED}
    ${If} $R8 != ${SF_SELECTED}
      RMDir /r "$INSTDIR\modules\clx.pet"
    ${EndIf}
    SectionGetFlags ${SEC_CLX_QUICKAPPS} $R8
    IntOp $R8 $R8 & ${SF_SELECTED}
    ${If} $R8 != ${SF_SELECTED}
      RMDir /r "$INSTDIR\modules\clx.quickapps"
    ${EndIf}
    SectionGetFlags ${SEC_CLX_SSH} $R8
    IntOp $R8 $R8 & ${SF_SELECTED}
    ${If} $R8 != ${SF_SELECTED}
      RMDir /r "$INSTDIR\modules\clx.ssh"
    ${EndIf}
  SectionEnd

  Function ClxInitializeModuleSelections
    ${If} ${FileExists} "$INSTDIR\modules\clx.ai-companion\*.*"
      SectionGetFlags ${SEC_CLX_AI_COMPANION} $R8
      IntOp $R8 $R8 | ${SF_SELECTED}
      SectionSetFlags ${SEC_CLX_AI_COMPANION} $R8
    ${EndIf}
    ${If} ${FileExists} "$INSTDIR\modules\clx.api-client\*.*"
      SectionGetFlags ${SEC_CLX_API_CLIENT} $R8
      IntOp $R8 $R8 | ${SF_SELECTED}
      SectionSetFlags ${SEC_CLX_API_CLIENT} $R8
    ${EndIf}
    ${If} ${FileExists} "$INSTDIR\modules\clx.buzz\*.*"
      SectionGetFlags ${SEC_CLX_BUZZ} $R8
      IntOp $R8 $R8 | ${SF_SELECTED}
      SectionSetFlags ${SEC_CLX_BUZZ} $R8
    ${EndIf}
    ${If} ${FileExists} "$INSTDIR\modules\clx.cli-proxy\*.*"
      SectionGetFlags ${SEC_CLX_CLI_PROXY} $R8
      IntOp $R8 $R8 | ${SF_SELECTED}
      SectionSetFlags ${SEC_CLX_CLI_PROXY} $R8
    ${EndIf}
    ${If} ${FileExists} "$INSTDIR\modules\clx.local-llm\*.*"
      SectionGetFlags ${SEC_CLX_LOCAL_LLM} $R8
      IntOp $R8 $R8 | ${SF_SELECTED}
      SectionSetFlags ${SEC_CLX_LOCAL_LLM} $R8
    ${EndIf}
    ${If} ${FileExists} "$INSTDIR\modules\clx.nes\*.*"
      SectionGetFlags ${SEC_CLX_NES} $R8
      IntOp $R8 $R8 | ${SF_SELECTED}
      SectionSetFlags ${SEC_CLX_NES} $R8
    ${EndIf}
    ${If} ${FileExists} "$INSTDIR\modules\clx.pet\*.*"
      SectionGetFlags ${SEC_CLX_PET} $R8
      IntOp $R8 $R8 | ${SF_SELECTED}
      SectionSetFlags ${SEC_CLX_PET} $R8
    ${EndIf}
    ${If} ${FileExists} "$INSTDIR\modules\clx.quickapps\*.*"
      SectionGetFlags ${SEC_CLX_QUICKAPPS} $R8
      IntOp $R8 $R8 | ${SF_SELECTED}
      SectionSetFlags ${SEC_CLX_QUICKAPPS} $R8
    ${EndIf}
    ${If} ${FileExists} "$INSTDIR\modules\clx.ssh\*.*"
      SectionGetFlags ${SEC_CLX_SSH} $R8
      IntOp $R8 $R8 | ${SF_SELECTED}
      SectionSetFlags ${SEC_CLX_SSH} $R8
    ${EndIf}
    ClearErrors
    ${GetOptions} $CMDLINE "/CLXMODULES=" $R7
    ${IfNot} ${Errors}
      ${If} $R7 == "all"
        SectionGetFlags ${SEC_CLX_AI_COMPANION} $R8
        IntOp $R8 $R8 | ${SF_SELECTED}
        SectionSetFlags ${SEC_CLX_AI_COMPANION} $R8
        SectionGetFlags ${SEC_CLX_API_CLIENT} $R8
        IntOp $R8 $R8 | ${SF_SELECTED}
        SectionSetFlags ${SEC_CLX_API_CLIENT} $R8
        SectionGetFlags ${SEC_CLX_BUZZ} $R8
        IntOp $R8 $R8 | ${SF_SELECTED}
        SectionSetFlags ${SEC_CLX_BUZZ} $R8
        SectionGetFlags ${SEC_CLX_CLI_PROXY} $R8
        IntOp $R8 $R8 | ${SF_SELECTED}
        SectionSetFlags ${SEC_CLX_CLI_PROXY} $R8
        SectionGetFlags ${SEC_CLX_LOCAL_LLM} $R8
        IntOp $R8 $R8 | ${SF_SELECTED}
        SectionSetFlags ${SEC_CLX_LOCAL_LLM} $R8
        SectionGetFlags ${SEC_CLX_NES} $R8
        IntOp $R8 $R8 | ${SF_SELECTED}
        SectionSetFlags ${SEC_CLX_NES} $R8
        SectionGetFlags ${SEC_CLX_PET} $R8
        IntOp $R8 $R8 | ${SF_SELECTED}
        SectionSetFlags ${SEC_CLX_PET} $R8
        SectionGetFlags ${SEC_CLX_QUICKAPPS} $R8
        IntOp $R8 $R8 | ${SF_SELECTED}
        SectionSetFlags ${SEC_CLX_QUICKAPPS} $R8
        SectionGetFlags ${SEC_CLX_SSH} $R8
        IntOp $R8 $R8 | ${SF_SELECTED}
        SectionSetFlags ${SEC_CLX_SSH} $R8
      ${ElseIf} $R7 == "none"
        SectionGetFlags ${SEC_CLX_AI_COMPANION} $R8
        IntOp $R8 $R8 & 0xFFFFFFFE
        SectionSetFlags ${SEC_CLX_AI_COMPANION} $R8
        SectionGetFlags ${SEC_CLX_API_CLIENT} $R8
        IntOp $R8 $R8 & 0xFFFFFFFE
        SectionSetFlags ${SEC_CLX_API_CLIENT} $R8
        SectionGetFlags ${SEC_CLX_BUZZ} $R8
        IntOp $R8 $R8 & 0xFFFFFFFE
        SectionSetFlags ${SEC_CLX_BUZZ} $R8
        SectionGetFlags ${SEC_CLX_CLI_PROXY} $R8
        IntOp $R8 $R8 & 0xFFFFFFFE
        SectionSetFlags ${SEC_CLX_CLI_PROXY} $R8
        SectionGetFlags ${SEC_CLX_LOCAL_LLM} $R8
        IntOp $R8 $R8 & 0xFFFFFFFE
        SectionSetFlags ${SEC_CLX_LOCAL_LLM} $R8
        SectionGetFlags ${SEC_CLX_NES} $R8
        IntOp $R8 $R8 & 0xFFFFFFFE
        SectionSetFlags ${SEC_CLX_NES} $R8
        SectionGetFlags ${SEC_CLX_PET} $R8
        IntOp $R8 $R8 & 0xFFFFFFFE
        SectionSetFlags ${SEC_CLX_PET} $R8
        SectionGetFlags ${SEC_CLX_QUICKAPPS} $R8
        IntOp $R8 $R8 & 0xFFFFFFFE
        SectionSetFlags ${SEC_CLX_QUICKAPPS} $R8
        SectionGetFlags ${SEC_CLX_SSH} $R8
        IntOp $R8 $R8 & 0xFFFFFFFE
        SectionSetFlags ${SEC_CLX_SSH} $R8
      ${Else}
        StrCpy $R6 ",$R7,"
        ${StrLoc} $R9 "$R6" ",clx.ai-companion," ">"
        SectionGetFlags ${SEC_CLX_AI_COMPANION} $R8
        ${If} $R9 == ""
          IntOp $R8 $R8 & 0xFFFFFFFE
        ${Else}
          IntOp $R8 $R8 | ${SF_SELECTED}
        ${EndIf}
        SectionSetFlags ${SEC_CLX_AI_COMPANION} $R8
        ${StrLoc} $R9 "$R6" ",clx.api-client," ">"
        SectionGetFlags ${SEC_CLX_API_CLIENT} $R8
        ${If} $R9 == ""
          IntOp $R8 $R8 & 0xFFFFFFFE
        ${Else}
          IntOp $R8 $R8 | ${SF_SELECTED}
        ${EndIf}
        SectionSetFlags ${SEC_CLX_API_CLIENT} $R8
        ${StrLoc} $R9 "$R6" ",clx.buzz," ">"
        SectionGetFlags ${SEC_CLX_BUZZ} $R8
        ${If} $R9 == ""
          IntOp $R8 $R8 & 0xFFFFFFFE
        ${Else}
          IntOp $R8 $R8 | ${SF_SELECTED}
        ${EndIf}
        SectionSetFlags ${SEC_CLX_BUZZ} $R8
        ${StrLoc} $R9 "$R6" ",clx.cli-proxy," ">"
        SectionGetFlags ${SEC_CLX_CLI_PROXY} $R8
        ${If} $R9 == ""
          IntOp $R8 $R8 & 0xFFFFFFFE
        ${Else}
          IntOp $R8 $R8 | ${SF_SELECTED}
        ${EndIf}
        SectionSetFlags ${SEC_CLX_CLI_PROXY} $R8
        ${StrLoc} $R9 "$R6" ",clx.local-llm," ">"
        SectionGetFlags ${SEC_CLX_LOCAL_LLM} $R8
        ${If} $R9 == ""
          IntOp $R8 $R8 & 0xFFFFFFFE
        ${Else}
          IntOp $R8 $R8 | ${SF_SELECTED}
        ${EndIf}
        SectionSetFlags ${SEC_CLX_LOCAL_LLM} $R8
        ${StrLoc} $R9 "$R6" ",clx.nes," ">"
        SectionGetFlags ${SEC_CLX_NES} $R8
        ${If} $R9 == ""
          IntOp $R8 $R8 & 0xFFFFFFFE
        ${Else}
          IntOp $R8 $R8 | ${SF_SELECTED}
        ${EndIf}
        SectionSetFlags ${SEC_CLX_NES} $R8
        ${StrLoc} $R9 "$R6" ",clx.pet," ">"
        SectionGetFlags ${SEC_CLX_PET} $R8
        ${If} $R9 == ""
          IntOp $R8 $R8 & 0xFFFFFFFE
        ${Else}
          IntOp $R8 $R8 | ${SF_SELECTED}
        ${EndIf}
        SectionSetFlags ${SEC_CLX_PET} $R8
        ${StrLoc} $R9 "$R6" ",clx.quickapps," ">"
        SectionGetFlags ${SEC_CLX_QUICKAPPS} $R8
        ${If} $R9 == ""
          IntOp $R8 $R8 & 0xFFFFFFFE
        ${Else}
          IntOp $R8 $R8 | ${SF_SELECTED}
        ${EndIf}
        SectionSetFlags ${SEC_CLX_QUICKAPPS} $R8
        ${StrLoc} $R9 "$R6" ",clx.ssh," ">"
        SectionGetFlags ${SEC_CLX_SSH} $R8
        ${If} $R9 == ""
          IntOp $R8 $R8 & 0xFFFFFFFE
        ${Else}
          IntOp $R8 $R8 | ${SF_SELECTED}
        ${EndIf}
        SectionSetFlags ${SEC_CLX_SSH} $R8
      ${EndIf}
    ${EndIf}
  FunctionEnd
!macroend

!macro CLX_MODULE_UNINSTALL
  RMDir /r "$INSTDIR\modules\clx.ai-companion"
  RMDir /r "$INSTDIR\modules\clx.api-client"
  RMDir /r "$INSTDIR\modules\clx.buzz"
  RMDir /r "$INSTDIR\modules\clx.cli-proxy"
  RMDir /r "$INSTDIR\modules\clx.local-llm"
  RMDir /r "$INSTDIR\modules\clx.nes"
  RMDir /r "$INSTDIR\modules\clx.pet"
  RMDir /r "$INSTDIR\modules\clx.quickapps"
  RMDir /r "$INSTDIR\modules\clx.ssh"
  RMDir "$INSTDIR\modules"
!macroend
